import os
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

# Add source code
src = Glob('*.c')
src += [cwd+'/../../central_gatt_write/src/gatt_write_common.c']
group = DefineGroup('Applications', src, depend = [''],CPPPATH = CPPPATH)

Return('group')
