import os
import rtconfig

# Check SDK 
SIFLI_SDK = os.getenv('SIFLI_SDK')
if not SIFLI_SDK:
    print("Please run set_env.bat in root folder of SIFLI SDK to set environment.")
    exit()
from building import *

PrepareEnv()
################################## change rtconfig.xxx to customize build ########################################
# print (rtconfig.OUTPUT_DIR)

# Add bootloader project
AddBootLoader(SIFLI_SDK,rtconfig.CHIP)

# Add LCPU project
AddLCPU(SIFLI_SDK,rtconfig.CHIP, "../../src/lcpu_img.c")

if( "58X" in rtconfig.CHIP):
    acpu_proj_path = '../acpu'
    acpu_proj_name = 'acpu'
    AddChildProj(acpu_proj_name, acpu_proj_path, False, core="ACPU")




    

# Set default compile options
SifliEnv()

TARGET = rtconfig.OUTPUT_DIR + rtconfig.TARGET_NAME + '.' + rtconfig.TARGET_EXT

# prepare building environment
objs = PrepareBuilding(None)
env = GetCurrentEnv()

# make a building
DoBuilding(TARGET, objs)

# Add flash table
#AddFTAB(SIFLI_SDK,rtconfig.CHIP)
AddChildProj('ftab', '../ftab', False, core="HCPU")

GenDownloadScript(env)
