// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: test_demo

#include "../ui.h"

// COMPONENT button1

lv_obj_t *ui_button1_create(lv_obj_t *comp_parent)
{

    lv_obj_t *cui_button1;
    cui_button1 = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_button1, 100);
    lv_obj_set_height(cui_button1, 50);
    lv_obj_set_x(cui_button1, -8);
    lv_obj_set_y(cui_button1, 144);
    lv_obj_set_align(cui_button1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(cui_button1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_button1, lv_color_hex(0x17F739), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON1_NUM);
    children[UI_COMP_BUTTON1_BUTTON1] = cui_button1;
    lv_obj_add_event_cb(cui_button1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_button1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_button1_create_hook(cui_button1);
    return cui_button1;
}

