// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: test_demo

#ifndef _UI_COMP_BUTTON1_H
#define _UI_COMP_BUTTON1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT button1
#define UI_COMP_BUTTON1_BUTTON1 0
#define _UI_COMP_BUTTON1_NUM 1
lv_obj_t *ui_button1_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
