// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: test_demo

#ifndef _TEST_DEMO_UI_COMP_HOOK_H
#define _TEST_DEMO_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_button1_create_hook(lv_obj_t *comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
