// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: test_demo

#include "../ui.h"

lv_obj_t *ui_Screen2;
lv_obj_t *ui_TextArea1;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Button4;

// event funtions
void ui_event_Button4(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x7472C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextArea1, 323);
    lv_obj_set_height(ui_TextArea1, 127);
    lv_obj_set_x(ui_TextArea1, -4);
    lv_obj_set_y(ui_TextArea1, -70);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea1, "Welcome to Siche Technology! May Siche thrive and achieve success in open source!");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    ui_Label4 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -143);
    lv_obj_set_y(ui_Label4, -175);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Screen2");

    ui_Button4 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 0);
    lv_obj_set_y(ui_Button4, 150);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if (ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_TextArea1 = NULL;
    ui_Label4 = NULL;
    ui_Button4 = NULL;

}
