// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: test_demo

#include "../ui.h"

lv_obj_t *ui_Screen1;
lv_obj_t *ui_Image2;
lv_obj_t *ui_Label3;
lv_obj_t *ui_button1;

// event funtions
void ui_event_button1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Screen1, lv_color_hex(0x120303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Screen1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_test_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -154);
    lv_obj_set_y(ui_Label3, -184);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label3, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Label3, "Screen1");
    lv_label_set_recolor(ui_Label3, "true");

    ui_button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_button1, 100);
    lv_obj_set_height(ui_button1, 50);
    lv_obj_set_x(ui_button1, 0);
    lv_obj_set_y(ui_button1, 150);
    lv_obj_set_align(ui_button1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_button1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button1, lv_color_hex(0x17F739), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_button1, ui_event_button1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if (ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image2 = NULL;
    ui_Label3 = NULL;
    ui_button1 = NULL;

}
